language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
- 10.8
cache:
  yarn: true
  directories:
  - node_modules
  - ~/.cache/Cypress
  - build
before_install:
- openssl aes-256-cbc -K $encrypted_63d69a2d54d1_key -iv $encrypted_63d69a2d54d1_iv
  -in cypress/fixtures/accounts.json.enc -out cypress/fixtures/accounts.json -d
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
env:
  - CI=false
jobs:
  include:
  - stage: build
    name: Build
    script:
    - yarn build
  - stage: test
    name: Translations
    script:
    - yarn intl:prepare
    - yarn intl:export
  - stage: test
    name: Unit tests
    script:
    - yarn test-unit:prepare
    - yarn test-unit
  - stage: test
    name: E2E tests
    script:
    - yarn test
